import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedinputwidget6/generated/GeneratedRectangle2Widget6.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedinputwidget6/generated/GeneratedIngreseelnombreWidget6.dart';

/* Component input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 385.0,
      height: 70.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 385.0,
              height: 70.0,
              child: GeneratedRectangle2Widget6(),
            ),
            Positioned(
              left: 66.72393798828125,
              top: 21.304351806640625,
              right: null,
              bottom: null,
              width: 178.26507568359375,
              height: 24.318845748901367,
              child: GeneratedIngreseelnombreWidget6(),
            )
          ]),
    ));
  }
}
