import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmateriaswidget/generated/GeneratedRectangle2Widget7.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmateriaswidget/generated/GeneratedInputWidget7.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmateriaswidget/generated/GeneratedBotonWidget3.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmateriaswidget/generated/GeneratedFondo21Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmateriaswidget/generated/GeneratedIngreselosdatosdelamateriaWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmateriaswidget/generated/GeneratedInputWidget8.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmateriaswidget/generated/GeneratedInputWidget9.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmateriaswidget/generated/GeneratedMenuinferiorWidget2.dart';

/* Frame materias
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMateriasWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedFondo21Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 681.0,
                child: GeneratedRectangle2Widget7(),
              ),
              Positioned(
                left: 31.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 35.0,
                child: GeneratedIngreselosdatosdelamateriaWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 49.0,
                child: GeneratedInputWidget7(),
              ),
              Positioned(
                left: 18.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 49.0,
                child: GeneratedInputWidget8(),
              ),
              Positioned(
                left: 19.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 49.0,
                child: GeneratedInputWidget9(),
              ),
              Positioned(
                left: 36.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 56.0,
                child: GeneratedBotonWidget3(),
              ),
              Positioned(
                left: 1.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 94.0,
                child: GeneratedMenuinferiorWidget2(),
              )
            ]),
      ),
    ));
  }
}
