import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedloginwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedloginwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedloginwidget/generated/GeneratedBienvenidoacontrolescolarCBTIS128Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedloginwidget/generated/GeneratedFondo11Widget.dart';

/* Frame login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedFondo11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 413.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 353.0,
                height: 84.0,
                child: GeneratedBienvenidoacontrolescolarCBTIS128Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 49.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 49.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 56.0,
                child: GeneratedBotonWidget(),
              )
            ]),
      ),
    ));
  }
}
