import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmenuinferiorwidget1/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmenuinferiorwidget1/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmenuinferiorwidget1/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmenuinferiorwidget1/generated/GeneratedGroup3Widget1.dart';

/* Component menu inferior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuinferiorWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 413.0,
      height: 94.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 410.0,
              height: 94.0,
              child: GeneratedRectangle5Widget1(),
            ),
            Positioned(
              left: 26.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 76.0,
              height: 69.0,
              child: GeneratedGroup2Widget1(),
            ),
            Positioned(
              left: 314.0,
              top: 13.0,
              right: null,
              bottom: null,
              width: 64.0,
              height: 74.0,
              child: GeneratedGroup4Widget1(),
            ),
            Positioned(
              left: 176.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 62.0,
              height: 82.0,
              child: GeneratedGroup3Widget1(),
            )
          ]),
    ));
  }
}
